# this configuration is only needed to setup the database for the tests

# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: db_test_postgresql
  username: rails
  password: 1qaz!QAZ
  host: 127.0.0.1
  pool: 50
  timeout: 5000
  min_messages: WARNING
  verbosity: quiet
